// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstate.Infrastructure.EfCore;

#nullable disable

namespace RealEstate.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    partial class RealEstateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstate.Domain.Models.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passport_number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_counterparty");

                    b.HasIndex("PassportNumber")
                        .HasDatabaseName("ix_counterparty_passport_number");

                    b.ToTable("counterparty", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Иванов Иван",
                            PassportNumber = "4010 111111",
                            Phone = "+7-900-000-01-01"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Петров Пётр",
                            PassportNumber = "4010 222222",
                            Phone = "+7-900-000-02-02"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров Степан",
                            PassportNumber = "4010 333333",
                            Phone = "+7-900-000-03-03"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Антонова Анна",
                            PassportNumber = "4010 444444",
                            Phone = "+7-900-000-04-04"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Кузнецов Кирилл",
                            PassportNumber = "4010 555555",
                            Phone = "+7-900-000-05-05"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Соколова Света",
                            PassportNumber = "4010 666666",
                            Phone = "+7-900-000-06-06"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Романов Роман",
                            PassportNumber = "4010 777777",
                            Phone = "+7-900-000-07-07"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Фёдорова Фаина",
                            PassportNumber = "4010 888888",
                            Phone = "+7-900-000-08-08"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Морозов Максим",
                            PassportNumber = "4010 999999",
                            Phone = "+7-900-000-09-09"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Ким Денис",
                            PassportNumber = "4010 101010",
                            Phone = "+7-900-000-10-10"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Осипова Олеся",
                            PassportNumber = "4010 111112",
                            Phone = "+7-900-000-11-11"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Громов Григорий",
                            PassportNumber = "4010 121212",
                            Phone = "+7-900-000-12-12"
                        });
                });

            modelBuilder.Entity("RealEstate.Domain.Models.RealEstateObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cadastral_number");

                    b.Property<double?>("CeilingHeightM")
                        .HasPrecision(4, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("ceiling_height");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<int>("FloorsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("floors_total");

                    b.Property<bool>("HasEncumbrances")
                        .HasColumnType("boolean")
                        .HasColumnName("has_encumbrances");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer")
                        .HasColumnName("rooms");

                    b.Property<double>("TotalAreaSqM")
                        .HasPrecision(12, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("total_area");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_real_estate_object");

                    b.ToTable("real_estate_object", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Москва, ул. Первая, 1",
                            CadastralNumber = "77:01:0001001:1",
                            CeilingHeightM = 2.7000000000000002,
                            Floor = 7,
                            FloorsTotal = 17,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 2,
                            TotalAreaSqM = 52.299999999999997,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "МО, Мытищи, ул. Лесная, 3",
                            CadastralNumber = "50:01:0002002:2",
                            CeilingHeightM = 3.0,
                            FloorsTotal = 2,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 5,
                            TotalAreaSqM = 180.0,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "СПб, Невский 10",
                            CadastralNumber = "78:01:0003003:3",
                            CeilingHeightM = 3.2000000000000002,
                            Floor = 3,
                            FloorsTotal = 8,
                            HasEncumbrances = true,
                            Purpose = 1,
                            Rooms = 4,
                            TotalAreaSqM = 95.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Краснодарский край, уч. 45",
                            CadastralNumber = "23:01:0004004:4",
                            CeilingHeightM = 0.0,
                            FloorsTotal = 0,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 0,
                            TotalAreaSqM = 1000.0,
                            Type = 6
                        },
                        new
                        {
                            Id = 5,
                            Address = "Екатеринбург, Промзона 12",
                            CadastralNumber = "66:01:0005005:5",
                            CeilingHeightM = 6.0,
                            Floor = 1,
                            FloorsTotal = 1,
                            HasEncumbrances = true,
                            Purpose = 1,
                            Rooms = 1,
                            TotalAreaSqM = 450.0,
                            Type = 5
                        },
                        new
                        {
                            Id = 6,
                            Address = "Москва, ул. Вторая, 5",
                            CadastralNumber = "77:01:0006006:6",
                            CeilingHeightM = 2.6000000000000001,
                            Floor = 16,
                            FloorsTotal = 25,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 1,
                            TotalAreaSqM = 40.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Москва, ул. Третья, 7",
                            CadastralNumber = "77:01:0007007:7",
                            CeilingHeightM = 2.6000000000000001,
                            Floor = 12,
                            FloorsTotal = 25,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 1,
                            TotalAreaSqM = 36.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "МО, Балашиха, Заречная 8",
                            CadastralNumber = "50:01:0008008:8",
                            CeilingHeightM = 2.8999999999999999,
                            FloorsTotal = 2,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 4,
                            TotalAreaSqM = 140.0,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "СПб, Сенная, 2",
                            CadastralNumber = "78:01:0009009:9",
                            CeilingHeightM = 3.2999999999999998,
                            Floor = 6,
                            FloorsTotal = 12,
                            HasEncumbrances = false,
                            Purpose = 1,
                            Rooms = 5,
                            TotalAreaSqM = 120.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Address = "Москва, ул. Новая, 9",
                            CadastralNumber = "77:01:0010010:0",
                            CeilingHeightM = 2.7999999999999998,
                            Floor = 9,
                            FloorsTotal = 22,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 3,
                            TotalAreaSqM = 58.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Address = "Краснодарский край, уч. 17",
                            CadastralNumber = "23:01:0011011:1",
                            CeilingHeightM = 0.0,
                            FloorsTotal = 0,
                            HasEncumbrances = false,
                            Purpose = 0,
                            Rooms = 0,
                            TotalAreaSqM = 800.0,
                            Type = 6
                        },
                        new
                        {
                            Id = 12,
                            Address = "Екатеринбург, ТЦ «Океан»",
                            CadastralNumber = "66:01:0012012:2",
                            CeilingHeightM = 3.3999999999999999,
                            Floor = 1,
                            FloorsTotal = 3,
                            HasEncumbrances = false,
                            Purpose = 1,
                            Rooms = 2,
                            TotalAreaSqM = 75.0,
                            Type = 4
                        });
                });

            modelBuilder.Entity("RealEstate.Domain.Models.RealEstateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_real_estate_request");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_real_estate_request_client_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_real_estate_request_property_id");

                    b.ToTable("real_estate_request", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000000m,
                            ClientId = 1,
                            CreatedAt = new DateOnly(2024, 6, 15),
                            PropertyId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10000000m,
                            ClientId = 2,
                            CreatedAt = new DateOnly(2024, 7, 20),
                            PropertyId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 15000000m,
                            ClientId = 3,
                            CreatedAt = new DateOnly(2024, 5, 10),
                            PropertyId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2000000m,
                            ClientId = 4,
                            CreatedAt = new DateOnly(2024, 6, 5),
                            PropertyId = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3000000m,
                            ClientId = 1,
                            CreatedAt = new DateOnly(2023, 1, 1),
                            PropertyId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3500000m,
                            ClientId = 5,
                            CreatedAt = new DateOnly(2024, 6, 18),
                            PropertyId = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1000000m,
                            ClientId = 6,
                            CreatedAt = new DateOnly(2024, 6, 19),
                            PropertyId = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 5000000m,
                            ClientId = 7,
                            CreatedAt = new DateOnly(2024, 7, 1),
                            PropertyId = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Amount = 2000000m,
                            ClientId = 6,
                            CreatedAt = new DateOnly(2024, 7, 2),
                            PropertyId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1000000m,
                            ClientId = 8,
                            CreatedAt = new DateOnly(2024, 7, 3),
                            PropertyId = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Amount = 1200000m,
                            ClientId = 8,
                            CreatedAt = new DateOnly(2024, 7, 4),
                            PropertyId = 11,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Amount = 2200000m,
                            ClientId = 9,
                            CreatedAt = new DateOnly(2024, 7, 5),
                            PropertyId = 12,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Amount = 4100000m,
                            ClientId = 5,
                            CreatedAt = new DateOnly(2024, 8, 1),
                            PropertyId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Amount = 4200000m,
                            ClientId = 5,
                            CreatedAt = new DateOnly(2024, 8, 2),
                            PropertyId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Amount = 7000000m,
                            ClientId = 3,
                            CreatedAt = new DateOnly(2024, 7, 15),
                            PropertyId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 12000000m,
                            ClientId = 2,
                            CreatedAt = new DateOnly(2024, 8, 10),
                            PropertyId = 7,
                            Type = 1
                        });
                });

            modelBuilder.Entity("RealEstate.Domain.Models.RealEstateRequest", b =>
                {
                    b.HasOne("RealEstate.Domain.Models.Counterparty", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_real_estate_request_client");

                    b.HasOne("RealEstate.Domain.Models.RealEstateObject", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_real_estate_request_property");

                    b.Navigation("Client");

                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
